#PRI SEMINARSKI NALOGI SEM UPORABIL NASLEDNJE KNJIZNICE:


library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(shiny)
library(readr)
library(dplyr)
library(tmap)
library(ggplot2)
library(grid)
library(rworldmap)
library(cowplot)
library(googleway)
library(ggrepel)
library(ggspatial)
library(rnaturalearth)
library(rnaturalearthdata)
library(RColorBrewer)
library(mgcv)
library(tidyverse)
library(shiny)
